# Generated by Django 2.2.5 on 2019-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='location',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='birthdate',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='other_mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
