# Generated by Django 2.2.5 on 2019-09-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190917_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(default='image/default.jpg', upload_to='image/profile/'),
        ),
    ]
