# Generated by Django 2.2.5 on 2019-09-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190917_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='profile_pic',
            new_name='pic',
        ),
    ]
