# Generated by Django 2.2.5 on 2019-09-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190917_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pic',
            field=models.ImageField(default='image/picd/default.jpg', upload_to='image/profile/'),
        ),
    ]
