# Generated by Django 2.2.5 on 2019-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdoner',
            name='mail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reportdoner',
            name='mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
