# Generated by Django 2.2.3 on 2019-10-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191014_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdoner',
            old_name='fullname',
            new_name='user',
        ),
    ]
