# Generated by Django 2.2.3 on 2019-10-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191015_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdoner',
            old_name='user',
            new_name='reportuseracc',
        ),
    ]
