# Generated by Django 2.2.3 on 2019-10-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bloodbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
