# Generated by Django 2.2.3 on 2019-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bloodbank_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
