# Generated by Django 2.2.3 on 2019-10-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bloodbank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('summry', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('pic', models.ImageField(default='image/picd/default.jpg', upload_to='image/event/')),
            ],
        ),
    ]
