# Generated by Django 2.2.3 on 2019-10-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliderimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summry', models.TextField(blank=True, max_length=500)),
                ('pic', models.ImageField(default='image/picd/default.jpg', upload_to='image/slide/')),
            ],
        ),
    ]
